version: '3.7'

services:
  api:
    image: 'demo-api'
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
  db:
    image: postgres:16.1
    ports:
      - "9001:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
volumes:
  data: